apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
  name: simple
spec:
  version: 3.2.2
  autoFormatFs: true
  nameNodes:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/hostname
              values:
                - worker-3.stackable.demo
        replicas: 1
        config:
          javaHome: /usr/lib/jvm/java-11-openjdk-amd64/
          dfsNamenodeNameDir: file:///tmp/hdfs/nn
          ipcAddress:
            port: 9000
          httpAddress:
            port: 60000
          metricsPort: 50000
  dataNodes:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/hostname
              values:
                - worker-1.stackable.demo
                - worker-2.stackable.demo
                - main-1.stackable.demo
        replicas: 3
        config:
          javaHome: /usr/lib/jvm/java-11-openjdk-amd64/
          dfsDatanodeNameDir: file:///tmp/hdfs/dn
          httpAddress:
            port: 61000
          metricsPort: 51000

